endpoints = {
    "STATIC": {"BASE_URL": "https://fantasy.premierleague.com/api/bootstrap-static/"},
    "API": {
        "BASE_URL": "https://fantasy.premierleague.com/",
        "AUTH": "https://account.premierleague.com/as/authorize",
        "LOGIN": "https://users.premierleague.com/accounts/login/",
        "MY_TEAM": "https://fantasy.premierleague.com/api/entry/{f}/",
        "USER_TEAM": "https://fantasy.premierleague.com/api/my-team/{f}/",
        "GET_PLAYER": "https://fantasy.premierleague.com/api/element-summary/{f}/",
        "MY_TEAM_GW": "https://fantasy.premierleague.com/api/entry/{f}/event/{gw}/picks",
        "GW_FIXTURES": "https://fantasy.premierleague.com/api/fixtures/?events={{f}}",
        "ALL_FIXTURES": "https://fantasy.premierleague.com/api/fixtures/",
        "ME": "https://fantasy.premierleague.com/api/me",
        "TRANSFERS": "https://fantasy.premierleague.com/api/transfers/",
        "REDIRECT_URI": "https://fantasy.premierleague.com/",
        "DAVINCI_POLICY_START": "https://account.premierleague.com/davinci/policy/262ce4b01d19dd9d385d26bddb4297b6/start",
        "DAVINCI_CONNECTIONS": "https://account.premierleague.com/davinci/connections/{}/capabilities/customHTMLTemplate",
        "AS_RESUME": "https://account.premierleague.com/as/resume",
        "AS_TOKEN": "https://account.premierleague.com/as/token",
     },
    "DATA_GITHUB": {
        "BASE_URL": "https://github.com/vaastav/Fantasy-Premier-League/blob/master/data/",
        "FOLDER_URL": "https://github.com/vaastav/Fantasy-Premier-League/tree/master/data",
    },
}
